services:    
    cart-node:
      env_file: 
        - ../environments/dev.env
      ports: 
        - 9091:9091
      networks:
       - shared-swarm-net-dev
  
  
    cart-db:
      ports:
         - 27018:27017
      networks:
       - shared-swarm-net-dev

    
    filebeat:
      networks:
         - shared-swarm-net-dev
