services:    
    cart-node-1:
      env_file: 
        - ../environments/prod.env
      ports: 
        - 9095:9095
      volumes:
         - C:/Users/User/certificates/self-signed-custom-ca/rootCA.crt:/var/lib/certs/rootCA.crt
         - C:/Users/User/certificates/self-signed-custom-ca/cart.key:/var/lib/certs/cart.key
         - C:/Users/User/certificates/self-signed-custom-ca/cart.crt:/var/lib/certs/cart.crt
      networks:
       - shared-swarm-net-prod
    
    cart-db:
      ports:
         - 27019:27017
      networks:
       - shared-swarm-net-prod
    
    filebeat:
      networks:
         - shared-swarm-net-prod
      