services:
    cart-node:
       deploy:
        replicas: 3
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.labels.role == worker1]
       volumes:
       - logs-volume:/var/log/cartmicrosvcs
       env_file: 
        - ../environments/common.env
       image: dockerenthusiast1992/cart-node-express
    

    cart-db:
      deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.labels.role == worker1]
      image: mongo:latest
      volumes:
         - mongo-data:/data/db

    filebeat:
      image: dockerenthusiast1992/cartmicrosvcs-filebeat
      deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.labels.role == worker1]
      environment:
         - strict.perms=false
      volumes:
         - logs-volume:/var/log/cartmicrosvcs/:ro

networks:
   shared-swarm-net-dev:
      external: true
   shared-swarm-net-prod:
      external: true
  

volumes:
  mongo-data:
  logs-volume:

  # In this example, mongo-data is a named volume that ensures all data written 
  # by the MongoDB container to /data/db (MongoDB's default data directory) is saved persistently 
  # on the host system, even if the mongodb container is removed or recreated.